### PR TITLE
flux: fix sorting on lastUpdated, source, age

### LINKED ISSUE #159: Flux plugin -  wrong sorting for age / last updated columns
Age and Last updated columns are not ordering correctly.

Image

Image

### PR DESCRIPTION
**Pull request by mgalesloot**
Fixes #159

### CODE REVIEW

File: flux/src/inventory/index.tsx [hunk 1]
```diff
@@ -99,7 +99,8 @@ export function GetResourcesFromInventory(props: {
           },
           {
             header: 'Age',
-            accessorFn: item => <DateLabel date={item?.metadata?.creationTimestamp} />,
+            accessorKey: 'metadata.creationTimestamp',
+            Cell: ({ cell }: any) => <DateLabel date={cell.getValue()} />,
```
Comment (ashu8912) [inline flux/src/inventory/index.tsx:103]: Screenshot 2025-02-20 at 12 00 25 PM
The inventory age column still doesn't seem to be sorted

**Review by ashu8912 — COMMENTED** [review]
The inventory age sorting seems to be broken, but lastUpdated for kustomization and source works

**Comment by mgalesloot** [comment]
Age sorting now also supported.

File: flux/src/common/Table.tsx [hunk 2]
```diff
@@ -116,11 +117,15 @@ export function Table(props: TableProps) {
             return {
               header: 'Source',
               accessorFn: item => {
-                const { name, type } = getSourceNameAndType(item);
+                const { name } = getSourceNameAndType(item);
+                return name;
+              },
+              Cell: ({ row }: any) => {
```
Comment (ashu8912) [inline flux/src/common/Table.tsx]: we can change this to {row: {original: item}} than we wouldn't need the below change

**Review by ashu8912 — COMMENTED** [review]
This file was added and removed later can we remove the commits as well if this is not required

File: flux/src/common/Table.tsx (hunk 2 above)
Comment (mgalesloot) [reply flux/src/common/Table.tsx]: This has been reworked to ` {row: {original: item}} `

**Comment by mgalesloot** [comment]
Commits have been rebased.

File: flux/src/inventory/index.tsx [hunk 3]
```diff
@@ -1,7 +1,7 @@
 import { K8s } from '@kinvolk/headlamp-plugin/lib';
 import { DateLabel, Link } from '@kinvolk/headlamp-plugin/lib/components/common';
 import { KubeObject } from '@kinvolk/headlamp-plugin/lib/lib/k8s/cluster';
-import React from 'react';
+import React, { cloneElement } from 'react';
```
Comment (viceice) [inline flux/src/inventory/index.tsx:4]: not used import
