### PR TITLE
Fix(karpenter): Restore missing menu items & set engine compatibility

### LINKED ISSUE #477: Karpenter: Menu only display nodeclass section
Image

As you can see here in, the karpenter menu only displays node class information.
From the demo there should be node class, node pool, pending pods & scaling view too.

This is the plugins manager configuration that I am using.

```
pluginsManager:
    enabled: true
    configContent: |
      plugins:
        - name: karpenter
          source: https://artifacthub.io/packages/headlamp/headlamp-plugins/headlamp_karpenter
          version: 0.1.0
      installOptions:
        parallel: true
        maxConcurrent: 2
```

### PR DESCRIPTION
**Pull request by RachanaVenkat**
## Description
This PR addresses a runtime error causing the Karpenter menu to only display the NodeClass section. It resolves the `undefined` error on `getMainAPIGroup` to ensure NodePool, Pending Pods, and Scaling views render correctly.

Additionally, this PR updates the plugin manifest to explicitly support newer Headlamp versions.

## Changes
- **Runtime Fix:** Patched `createNodeClassClass.ts` and List views to mock the `customResourceDefinition` property. This satisfies the Headlamp runtime requirement and prevents `getMainAPIGroup` failures.
- **Compatibility:** Added the `engines` field to `package.json` to declare support for Headlamp `>=0.20.0`. This resolves "Incompatible" errors on updated clusters.
pr1
pr2
Screenshot 2026-01-22 at 12 28 39 PM
Screenshot 2026-01-22 at 12 29 03 PM

## Testing
- Verified on local Kind cluster.
- Verified on EKS (Headlamp v0.39.0).
- All list views (Node Class, Node Pool, Scaling) now render correctly without crashing.

## Fixes
Fixes #477

### CODE REVIEW

File: karpenter/src/helpers/createNodeClassClass.ts [hunk 1]
```diff
@@ -33,5 +35,9 @@ export function createNodeClassClass(config) {
     static get kind() {
       return config.kind;
     }
+
+    static getMainAPIGroup() {
+      return `${config.group}/${config.version}`;
+    }
```
[the remark this answers is not in the document]
Comment (RachanaVenkat) [reply karpenter/src/helpers/createNodeClassClass.ts:41]: Standardized the getMainAPIGroup static method to return an array [config.group, config.version] (instead of a string format). This ensures consistency with the customResourceDefinition mock and prevents runtime destructuring errors in Headlamp's base class.

File: karpenter/src/NodePool/List.tsx [hunk 2]
```diff
@@ -25,13 +25,19 @@ export function nodePoolClass() {
...
+    } as any,
   });
 
   return class extendedNodePoolClass extends NodePool {
     static get detailsRoute() {
       return 'nodepools-detail';
     }
+
+    static getMainAPIGroup() {
+      return 'karpenter.sh/v1';
```
[the remark this answers is not in the document]
Comment (RachanaVenkat) [reply karpenter/src/NodePool/List.tsx]: Standardized the return type to an array [nodePoolGroup, nodePoolVersion] to match the mock definition. Also replaced the hardcoded string with scope variables for improved maintainability.

**Review by illume — CHANGES_REQUESTED** [review]
Thanks for this!

Please see the [git commit guidelines](https://headlamp.dev/docs/latest/contributing#2-follow-commit-guidelines) and look at other git log messages.

Something like:
> karpenter: NodePool: Scaling:  createNodeClassClass: Restore missing menu sections

File: karpenter/package.json [hunk 3]
```diff
@@ -2,6 +2,7 @@
   "name": "@headlamp-k8s/karpenter",
   "version": "0.1.0",
   "description": "A Headlamp plugin that provides a UI for visualizing and managing Karpenter's autoscaling decisions, custom resources, and provisioning behavior in real-time. (Alpha Release)",
+  "main": "dist/main.js",
```
Comment (illume) [inline karpenter/package.json:5]: Sorry, I just noticed this.

>  "main": "dist/main.js",

What is this for? We don't use it in any of the other plugins, so I'm a bit afraid of adding it here.

Comment (illume) [reply karpenter/package.json:5]: I don't think it will be used because plugins don't use this, but also I guess it doesn't hurt.

Comment (RachanaVenkat) [reply karpenter/package.json:5]: My bad, that was a leftover from some local troubleshooting. Thanks for pointing it out and for the merge! I'll keep an eye on that for next time.
